// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIzIV-VHhs4EwbZDxbMkV3FEJbJuVePSc',
    appId: '1:211192575535:web:6e3e3d042294cc14b3f8da',
    messagingSenderId: '211192575535',
    projectId: 'fire-auth-5c1e5',
    authDomain: 'fire-auth-5c1e5.firebaseapp.com',
    storageBucket: 'fire-auth-5c1e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGx8y90H2rUnZLS7fQiwdVxKMr0tCp9Q',
    appId: '1:211192575535:android:d700873ccb80905fb3f8da',
    messagingSenderId: '211192575535',
    projectId: 'fire-auth-5c1e5',
    storageBucket: 'fire-auth-5c1e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6q0zC9_vtzwaGaSc8b0kcIV75L1BgGs',
    appId: '1:211192575535:ios:8d6dce7798aa8e61b3f8da',
    messagingSenderId: '211192575535',
    projectId: 'fire-auth-5c1e5',
    storageBucket: 'fire-auth-5c1e5.appspot.com',
    androidClientId: '211192575535-sq4v33b6dpk3dthjos3nf2flmkd1gadh.apps.googleusercontent.com',
    iosClientId: '211192575535-hkonk459tfq1mq332hobpgc30ocfnt9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6q0zC9_vtzwaGaSc8b0kcIV75L1BgGs',
    appId: '1:211192575535:ios:8d6dce7798aa8e61b3f8da',
    messagingSenderId: '211192575535',
    projectId: 'fire-auth-5c1e5',
    storageBucket: 'fire-auth-5c1e5.appspot.com',
    androidClientId: '211192575535-sq4v33b6dpk3dthjos3nf2flmkd1gadh.apps.googleusercontent.com',
    iosClientId: '211192575535-hkonk459tfq1mq332hobpgc30ocfnt9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
